using PlumePdf.Compose;
using PlumePdf.Documents;
using PlumePdf.Elements;
using Xunit;

namespace PlumePdf.Tests.Documents;

/// <summary>
/// <see cref="TextExtractor"/> letter production, driven by round-trip fixtures
/// generated by Phase 2's own writer (<see cref="PdfDocument.Compose"/>) — the two subsystems
/// verify each other.
/// </summary>
public class TextExtractionTests
{
    [Fact]
    public void ExtractText_ComposedSinglePage_RecoversExactTextInReadingOrder()
    {
        using var document = PdfDocument.Compose(page =>
        {
            page.Size(PageSize.A4).Margin(40);
            page.Content().Text("Bill to Acme Corp");
        });

        var extracted = document.Pages[0].ExtractText();

        Assert.Equal("Bill to Acme Corp", extracted.Text);
        Assert.Single(extracted.Lines);
        Assert.Equal(["Bill", "to", "Acme", "Corp"], extracted.Words.Select(w => w.Text));
        Assert.True(extracted.Letters.Count > 10);
    }

    [Fact]
    public void ExtractText_ComposedSinglePage_LettersHavePositiveFontSizeAndFiniteCoordinates()
    {
        using var document = PdfDocument.Compose(page =>
        {
            page.Size(PageSize.A4).Margin(40);
            page.Content().Text("Positioned text");
        });

        var extracted = document.Pages[0].ExtractText();

        Assert.NotEmpty(extracted.Letters);
        foreach (var letter in extracted.Letters)
        {
            Assert.True(letter.FontSize > 0);
            Assert.True(double.IsFinite(letter.X));
            Assert.True(double.IsFinite(letter.Y));
            Assert.True(double.IsFinite(letter.BoundingBox.Width));
        }
    }

    [Fact]
    public void ExtractText_LettersAdvanceLeftToRightWithinAWord()
    {
        using var document = PdfDocument.Compose(page =>
        {
            page.Size(PageSize.A4).Margin(40);
            page.Content().Text("Hello");
        });

        var extracted = document.Pages[0].ExtractText();
        var word = extracted.Words.Single();

        for (var i = 1; i < word.Letters.Count; i++)
        {
            Assert.True(word.Letters[i].X > word.Letters[i - 1].X, $"Letter {i} ('{word.Letters[i].Value}') did not advance past letter {i - 1} ('{word.Letters[i - 1].Value}').");
        }
    }

    [Fact]
    public void ExtractText_EmptyPage_ReturnsEmptyResultWithNoDiagnostics()
    {
        using var document = PdfDocument.Compose(page =>
        {
            page.Size(PageSize.A4).Margin(40);
            page.Content().Text(" ");
        });

        var extracted = document.Pages[0].ExtractText();

        Assert.NotNull(extracted.Text);
        Assert.NotNull(extracted.Diagnostics);
    }

    [Fact]
    public void ExtractText_NullOptions_UsesDefaults()
    {
        using var document = PdfDocument.Compose(page =>
        {
            page.Size(PageSize.A4).Margin(40);
            page.Content().Text("Defaults");
        });

        var extracted = document.Pages[0].ExtractText(options: null);

        Assert.Equal("Defaults", extracted.Text);
    }

    [Fact]
    public void ExtractText_MaxLettersPerPageOverride_ThrowsPlume6021()
    {
        using var document = PdfDocument.Compose(page =>
        {
            page.Size(PageSize.A4).Margin(40);
            page.Content().Text("This sentence has more than a couple of letters in it.");
        });

        var options = new PdfTextExtractionOptions { MaxLettersPerPage = 3 };
        var ex = Assert.Throws<PlumePdfException>(() => document.Pages[0].ExtractText(options));
        Assert.Equal("PLUME6021", ex.Code);
    }
}
