#!/usr/bin/env dotnet-script
// Dev-time generator: reads Adobe's Core 14 AFM files from corpora/afm/
// (fetched by scripts/fetch-corpora.sh — never committed) and emits the two static,
// AOT-safe C# tables checked into src/PlumePdf/Fonts/Standard14/:
//   Standard14Metrics.g.cs     — glyph-name-keyed advance widths + font-wide metrics
//   Standard14Encodings.g.cs   — WinAnsiEncoding + Symbol/ZapfDingbats built-in encodings
//
// This script is NOT run in CI and is NOT shipped — it is a one-time (or on-AFM-update)
// authoring tool. The checked-in .g.cs files are the actual build input. Run it with:
//   bash scripts/fetch-corpora.sh   # fetches corpora/afm/*.afm if not already present
//   dotnet script scripts/generate-standard14.csx
//
// Provenance: Adobe Systems Incorporated's Core 14 PostScript AFM files, Copyright (c)
// 1985, 1987, 1989, 1990, 1997 Adobe Systems Incorporated. All Rights Reserved.
// Redistributed under the accompanying Adobe AFM license (see NOTICE, docs/spec-sources.md).
// WinAnsiEncoding is transcribed from ISO 32000-1 Annex D.2 — a data table of code/glyph-
// name/Unicode facts, not spec prose (32000-1 is Adobe-free, so the clean-room policy's
// paywalled-spec clause does not bite, and data tables are facts, not prose).
#r "nuget: System.Collections.Immutable, 8.0.0"

using System.Text;
using System.Text.RegularExpressions;

var repoRoot = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(Args.Count > 0 ? Args[0] : AppContext.BaseDirectory) ?? ".", ".."));
var afmDir = Path.Combine(Directory.GetCurrentDirectory(), "corpora", "afm");
var outDir = Path.Combine(Directory.GetCurrentDirectory(), "src", "PlumePdf", "Fonts", "Standard14");

var fonts = new (string BaseName, string FileName)[]
{
    ("Helvetica", "Helvetica.afm"),
    ("Helvetica-Bold", "Helvetica-Bold.afm"),
    ("Helvetica-Oblique", "Helvetica-Oblique.afm"),
    ("Helvetica-BoldOblique", "Helvetica-BoldOblique.afm"),
    ("Times-Roman", "Times-Roman.afm"),
    ("Times-Bold", "Times-Bold.afm"),
    ("Times-Italic", "Times-Italic.afm"),
    ("Times-BoldItalic", "Times-BoldItalic.afm"),
    ("Courier", "Courier.afm"),
    ("Courier-Bold", "Courier-Bold.afm"),
    ("Courier-Oblique", "Courier-Oblique.afm"),
    ("Courier-BoldOblique", "Courier-BoldOblique.afm"),
    ("Symbol", "Symbol.afm"),
    ("ZapfDingbats", "ZapfDingbats.afm"),
};

(Dictionary<string, string> Header, Dictionary<string, int> Widths, Dictionary<int, string> CodeToName) ParseAfm(string path)
{
    var header = new Dictionary<string, string>();
    var widths = new Dictionary<string, int>();
    var codeToName = new Dictionary<int, string>();
    var charRegex = new Regex(@"C\s+(-?\d+)\s*;\s*WX\s+(-?\d+)\s*;\s*N\s+(\S+)\s*;");

    foreach (var line in File.ReadLines(path, Encoding.Latin1))
    {
        if (line.StartsWith("C ", StringComparison.Ordinal))
        {
            var m = charRegex.Match(line);
            if (m.Success)
            {
                var code = int.Parse(m.Groups[1].Value);
                var width = Math.Max(0, int.Parse(m.Groups[2].Value));
                var name = m.Groups[3].Value;
                widths[name] = width;
                if (code >= 0)
                {
                    codeToName[code] = name;
                }
            }

            continue;
        }

        foreach (var key in new[] { "Ascender", "Descender", "CapHeight", "XHeight", "ItalicAngle", "IsFixedPitch", "FontBBox" })
        {
            if (line.StartsWith(key + " ", StringComparison.Ordinal))
            {
                header[key] = line[(key.Length + 1)..].Trim();
            }
        }
    }

    return (header, widths, codeToName);
}

Directory.CreateDirectory(outDir);

var metricsCode = new StringBuilder();
metricsCode.AppendLine("// <auto-generated>");
metricsCode.AppendLine("// Generated by scripts/generate-standard14.csx from the Adobe Core 14 AFM files.");
metricsCode.AppendLine("// Source: Adobe Systems Incorporated's Core 14 PostScript AFM files (Copyright (c)");
metricsCode.AppendLine("// 1985, 1987, 1989, 1990, 1997 Adobe Systems Incorporated. All Rights Reserved.),");
metricsCode.AppendLine("// redistributed per the accompanying Adobe AFM license (see NOTICE and");
metricsCode.AppendLine("// docs/spec-sources.md for provenance). Do not edit by hand — re-run the generator.");
metricsCode.AppendLine("// </auto-generated>");
metricsCode.AppendLine();
metricsCode.AppendLine("using System.Collections.Frozen;");
metricsCode.AppendLine();
metricsCode.AppendLine("namespace PlumePdf.Fonts.Standard14;");
metricsCode.AppendLine();
metricsCode.AppendLine("/// <summary>");
metricsCode.AppendLine("/// Glyph-name-keyed advance widths (AFM <c>WX</c>, in 1000-unit glyph space) and");
metricsCode.AppendLine("/// font-wide metrics for each of the 14 standard PDF fonts (ISO 32000-1 §9.6.2.2),");
metricsCode.AppendLine("/// source-generated from Adobe's own Core 14 AFM files by");
metricsCode.AppendLine("/// <c>scripts/generate-standard14.csx</c>. See <c>docs/spec-sources.md</c> and");
metricsCode.AppendLine("/// <c>NOTICE</c> for provenance.");
metricsCode.AppendLine("/// </summary>");
metricsCode.AppendLine("internal static class Standard14Metrics");
metricsCode.AppendLine("{");
metricsCode.AppendLine("    /// <summary>One standard font's metrics: font-wide values plus its glyph-name-keyed advance widths.</summary>");
metricsCode.AppendLine("    internal readonly record struct FontMetrics(");
metricsCode.AppendLine("        double Ascender,");
metricsCode.AppendLine("        double Descender,");
metricsCode.AppendLine("        double CapHeight,");
metricsCode.AppendLine("        double XHeight,");
metricsCode.AppendLine("        double ItalicAngle,");
metricsCode.AppendLine("        bool IsFixedPitch,");
metricsCode.AppendLine("        double BBoxXMin,");
metricsCode.AppendLine("        double BBoxYMin,");
metricsCode.AppendLine("        double BBoxXMax,");
metricsCode.AppendLine("        double BBoxYMax,");
metricsCode.AppendLine("        FrozenDictionary<string, ushort> GlyphWidths);");
metricsCode.AppendLine();
metricsCode.AppendLine("    /// <summary>Every standard font's metrics, keyed by its PDF <c>/BaseFont</c> name.</summary>");
metricsCode.AppendLine("    internal static readonly FrozenDictionary<string, FontMetrics> ByFontName = BuildTable().ToFrozenDictionary();");
metricsCode.AppendLine();
metricsCode.AppendLine("    private static Dictionary<string, FontMetrics> BuildTable()");
metricsCode.AppendLine("    {");
metricsCode.AppendLine("        var table = new Dictionary<string, FontMetrics>(14, StringComparer.Ordinal);");
metricsCode.AppendLine();

var allParsed = new Dictionary<string, (Dictionary<string, string> Header, Dictionary<string, int> Widths, Dictionary<int, string> CodeToName)>();

foreach (var (baseName, fileName) in fonts)
{
    var parsed = ParseAfm(Path.Combine(afmDir, fileName));
    allParsed[baseName] = parsed;

    var varName = "widths_" + baseName.Replace("-", "_");
    metricsCode.AppendLine($"        var {varName} = new Dictionary<string, ushort>({parsed.Widths.Count}, StringComparer.Ordinal)");
    metricsCode.AppendLine("        {");
    foreach (var (name, width) in parsed.Widths)
    {
        metricsCode.AppendLine($"            [\"{name}\"] = {width},");
    }

    metricsCode.AppendLine("        }.ToFrozenDictionary();");

    var bbox = (parsed.Header.GetValueOrDefault("FontBBox", "0 0 0 0")).Split(' ', StringSplitOptions.RemoveEmptyEntries);
    while (bbox.Length < 4)
    {
        bbox = [.. bbox, "0"];
    }

    var ascender = parsed.Header.GetValueOrDefault("Ascender", "0");
    var descender = parsed.Header.GetValueOrDefault("Descender", "0");
    var capHeight = parsed.Header.GetValueOrDefault("CapHeight", "0");
    var xHeight = parsed.Header.GetValueOrDefault("XHeight", "0");
    var italicAngle = parsed.Header.GetValueOrDefault("ItalicAngle", "0");
    var fixedPitch = parsed.Header.GetValueOrDefault("IsFixedPitch", "false") == "true" ? "true" : "false";

    metricsCode.AppendLine($"        table[\"{baseName}\"] = new FontMetrics({ascender}, {descender}, {capHeight}, {xHeight}, {italicAngle}, {fixedPitch}, {bbox[0]}, {bbox[1]}, {bbox[2]}, {bbox[3]}, {varName});");
    metricsCode.AppendLine();
}

metricsCode.AppendLine("        return table;");
metricsCode.AppendLine("    }");
metricsCode.AppendLine("}");

File.WriteAllText(Path.Combine(outDir, "Standard14Metrics.g.cs"), metricsCode.ToString());
Console.WriteLine($"wrote Standard14Metrics.g.cs ({allParsed.Values.Sum(v => v.Widths.Count)} glyph entries)");

// --- Encodings -------------------------------------------------------------------
// WinAnsiEncoding (ISO 32000-1 Annex D.2) is a fixed, well-known 256-entry table — kept as
// data literals directly in this script (not re-derived from any AFM, since AFMs declare
// AdobeStandardEncoding, not WinAnsi) rather than parsed from anywhere.
var winAnsiAscii = new (int Code, string Name)[]
{
    (0x20, "space"), (0x21, "exclam"), (0x22, "quotedbl"), (0x23, "numbersign"), (0x24, "dollar"),
    (0x25, "percent"), (0x26, "ampersand"), (0x27, "quotesingle"), (0x28, "parenleft"), (0x29, "parenright"),
    (0x2A, "asterisk"), (0x2B, "plus"), (0x2C, "comma"), (0x2D, "hyphen"), (0x2E, "period"), (0x2F, "slash"),
    (0x30, "zero"), (0x31, "one"), (0x32, "two"), (0x33, "three"), (0x34, "four"), (0x35, "five"),
    (0x36, "six"), (0x37, "seven"), (0x38, "eight"), (0x39, "nine"),
    (0x3A, "colon"), (0x3B, "semicolon"), (0x3C, "less"), (0x3D, "equal"), (0x3E, "greater"), (0x3F, "question"),
    (0x40, "at"),
    (0x5B, "bracketleft"), (0x5C, "backslash"), (0x5D, "bracketright"), (0x5E, "asciicircum"), (0x5F, "underscore"),
    (0x60, "grave"),
    (0x7B, "braceleft"), (0x7C, "bar"), (0x7D, "braceright"), (0x7E, "asciitilde"),
};

var winAnsi = new (string Name, int Unicode)[256];
for (var c = 0; c < 256; c++)
{
    winAnsi[c] = ("", -1);
}

foreach (var (code, name) in winAnsiAscii)
{
    winAnsi[code] = (name, code);
}

for (var c = 0x41; c < 0x5B; c++)
{
    winAnsi[c] = (((char)c).ToString(), c);
}

for (var c = 0x61; c < 0x7B; c++)
{
    winAnsi[c] = (((char)c).ToString(), c);
}

var cp1252Block = new (int Code, string Name, int Unicode)[]
{
    (0x80, "Euro", 0x20AC), (0x81, "bullet", 0x2022), (0x82, "quotesinglbase", 0x201A),
    (0x83, "florin", 0x0192), (0x84, "quotedblbase", 0x201E), (0x85, "ellipsis", 0x2026),
    (0x86, "dagger", 0x2020), (0x87, "daggerdbl", 0x2021), (0x88, "circumflex", 0x02C6),
    (0x89, "perthousand", 0x2030), (0x8A, "Scaron", 0x0160), (0x8B, "guilsinglleft", 0x2039),
    (0x8C, "OE", 0x0152), (0x8D, "bullet", 0x2022), (0x8E, "Zcaron", 0x017D), (0x8F, "bullet", 0x2022),
    (0x90, "bullet", 0x2022), (0x91, "quoteleft", 0x2018), (0x92, "quoteright", 0x2019),
    (0x93, "quotedblleft", 0x201C), (0x94, "quotedblright", 0x201D), (0x95, "bullet", 0x2022),
    (0x96, "endash", 0x2013), (0x97, "emdash", 0x2014), (0x98, "tilde", 0x02DC),
    (0x99, "trademark", 0x2122), (0x9A, "scaron", 0x0161), (0x9B, "guilsinglright", 0x203A),
    (0x9C, "oe", 0x0153), (0x9D, "bullet", 0x2022), (0x9E, "zcaron", 0x017E), (0x9F, "Ydieresis", 0x0178),
};
foreach (var (code, name, unicode) in cp1252Block)
{
    winAnsi[code] = (name, unicode);
}

var latin1Names = new (int Code, string Name)[]
{
    (0xA1, "exclamdown"), (0xA2, "cent"), (0xA3, "sterling"), (0xA4, "currency"), (0xA5, "yen"),
    (0xA6, "brokenbar"), (0xA7, "section"), (0xA8, "dieresis"), (0xA9, "copyright"), (0xAA, "ordfeminine"),
    (0xAB, "guillemotleft"), (0xAC, "logicalnot"), (0xAE, "registered"), (0xAF, "macron"),
    (0xB0, "degree"), (0xB1, "plusminus"), (0xB2, "twosuperior"), (0xB3, "threesuperior"), (0xB4, "acute"),
    (0xB5, "mu"), (0xB6, "paragraph"), (0xB7, "periodcentered"), (0xB8, "cedilla"), (0xB9, "onesuperior"),
    (0xBA, "ordmasculine"), (0xBB, "guillemotright"), (0xBC, "onequarter"), (0xBD, "onehalf"),
    (0xBE, "threequarters"), (0xBF, "questiondown"),
    (0xC0, "Agrave"), (0xC1, "Aacute"), (0xC2, "Acircumflex"), (0xC3, "Atilde"), (0xC4, "Adieresis"),
    (0xC5, "Aring"), (0xC6, "AE"), (0xC7, "Ccedilla"), (0xC8, "Egrave"), (0xC9, "Eacute"),
    (0xCA, "Ecircumflex"), (0xCB, "Edieresis"), (0xCC, "Igrave"), (0xCD, "Iacute"), (0xCE, "Icircumflex"),
    (0xCF, "Idieresis"), (0xD0, "Eth"), (0xD1, "Ntilde"), (0xD2, "Ograve"), (0xD3, "Oacute"),
    (0xD4, "Ocircumflex"), (0xD5, "Otilde"), (0xD6, "Odieresis"), (0xD7, "multiply"), (0xD8, "Oslash"),
    (0xD9, "Ugrave"), (0xDA, "Uacute"), (0xDB, "Ucircumflex"), (0xDC, "Udieresis"), (0xDD, "Yacute"),
    (0xDE, "Thorn"), (0xDF, "germandbls"),
    (0xE0, "agrave"), (0xE1, "aacute"), (0xE2, "acircumflex"), (0xE3, "atilde"), (0xE4, "adieresis"),
    (0xE5, "aring"), (0xE6, "ae"), (0xE7, "ccedilla"), (0xE8, "egrave"), (0xE9, "eacute"),
    (0xEA, "ecircumflex"), (0xEB, "edieresis"), (0xEC, "igrave"), (0xED, "iacute"), (0xEE, "icircumflex"),
    (0xEF, "idieresis"), (0xF0, "eth"), (0xF1, "ntilde"), (0xF2, "ograve"), (0xF3, "oacute"),
    (0xF4, "ocircumflex"), (0xF5, "otilde"), (0xF6, "odieresis"), (0xF7, "divide"), (0xF8, "oslash"),
    (0xF9, "ugrave"), (0xFA, "uacute"), (0xFB, "ucircumflex"), (0xFC, "udieresis"), (0xFD, "yacute"),
    (0xFE, "thorn"), (0xFF, "ydieresis"),
};
foreach (var (code, name) in latin1Names)
{
    winAnsi[code] = (name, code);
}

winAnsi[0xA0] = ("space", 0x00A0);
winAnsi[0xAD] = ("hyphen", 0x00AD);

var encodingsCode = new StringBuilder();
encodingsCode.AppendLine("// <auto-generated>");
encodingsCode.AppendLine("// Generated by scripts/generate-standard14.csx.");
encodingsCode.AppendLine("// WinAnsiEncoding transcribed from ISO 32000-1 Annex D.2 (a data table of code/glyph-name/");
encodingsCode.AppendLine("// Unicode facts, not spec prose).");
encodingsCode.AppendLine("// Symbol/ZapfDingbats use their own AFM-declared built-in encodings; their Unicode column");
encodingsCode.AppendLine("// follows the conventional Private Use Area mapping (U+F000 + code) used when these fonts");
encodingsCode.AppendLine("// are addressed by codepoint rather than by raw character code. Do not edit by hand.");
encodingsCode.AppendLine("// </auto-generated>");
encodingsCode.AppendLine();
encodingsCode.AppendLine("namespace PlumePdf.Fonts.Standard14;");
encodingsCode.AppendLine();
encodingsCode.AppendLine("/// <summary>");
encodingsCode.AppendLine("/// Built-in encodings for the 14 standard PDF fonts: <see cref=\"WinAnsiEncoding\"/> for the");
encodingsCode.AppendLine("/// 12 text fonts (Helvetica/Times/Courier families), and each of <see cref=\"SymbolEncoding\"/>/");
encodingsCode.AppendLine("/// <see cref=\"ZapfDingbatsEncoding\"/> for its own symbol font (ISO 32000-1 §9.6.6, Annex D).");
encodingsCode.AppendLine("/// Each entry is (glyph name, Unicode codepoint); an unassigned code is (\"\", -1).");
encodingsCode.AppendLine("/// </summary>");
encodingsCode.AppendLine("internal static class Standard14Encodings");
encodingsCode.AppendLine("{");
encodingsCode.AppendLine("    /// <summary>ISO 32000-1 Annex D.2 WinAnsiEncoding, indexed by byte code 0-255.</summary>");
encodingsCode.AppendLine("    internal static readonly (string GlyphName, int Unicode)[] WinAnsiEncoding =");
encodingsCode.AppendLine("    [");
foreach (var (name, unicode) in winAnsi)
{
    encodingsCode.AppendLine($"        (\"{name}\", {unicode}),");
}

encodingsCode.AppendLine("    ];");
encodingsCode.AppendLine();

foreach (var (encName, baseName) in new[] { ("SymbolEncoding", "Symbol"), ("ZapfDingbatsEncoding", "ZapfDingbats") })
{
    var codeToName = allParsed[baseName].CodeToName;
    var table = new (string Name, int Unicode)[256];
    for (var c = 0; c < 256; c++)
    {
        table[c] = ("", -1);
    }

    foreach (var (code, name) in codeToName)
    {
        if (code is >= 0 and < 256)
        {
            table[code] = (name, 0xF000 + code);
        }
    }

    encodingsCode.AppendLine($"    /// <summary>{baseName}'s built-in encoding, as declared by its own AFM (PUA-mapped Unicode column, see file header).</summary>");
    encodingsCode.AppendLine($"    internal static readonly (string GlyphName, int Unicode)[] {encName} =");
    encodingsCode.AppendLine("    [");
    foreach (var (name, unicode) in table)
    {
        encodingsCode.AppendLine($"        (\"{name}\", {unicode}),");
    }

    encodingsCode.AppendLine("    ];");
    encodingsCode.AppendLine();
}

encodingsCode.AppendLine("}");

File.WriteAllText(Path.Combine(outDir, "Standard14Encodings.g.cs"), encodingsCode.ToString());
Console.WriteLine("wrote Standard14Encodings.g.cs");
