// <auto-generated>
// Generated by tools/FontAssetGen — do not edit by hand.
// Indexes every compiled-in substitute-font blob by face key by name (a plain switch, not
// reflection/Assembly.GetTypes — SubstituteFontStore's lookup stays AOT/trim-safe and clear
// of ReflectionBanTests without any gate change.
// </auto-generated>

namespace PlumePdf.Fonts.Substitute;

/// <summary>Name-keyed lookup over every compiled-in substitute-font blob this build generated.</summary>
internal static class SubstituteFontBlobs
{
    /// <summary>Every bundled face key this build compiled in, e.g. for AOT-smoke enumeration.</summary>
    public static readonly string[] FaceKeys = ["LiberationMono-Bold", "LiberationMono-BoldItalic", "LiberationMono-Italic", "LiberationMono-Regular", "LiberationSans-Bold", "LiberationSans-BoldItalic", "LiberationSans-Italic", "LiberationSans-Regular", "LiberationSerif-Bold", "LiberationSerif-BoldItalic", "LiberationSerif-Italic", "LiberationSerif-Regular"];

    /// <summary>Looks up a compiled-in face's raw font bytes by key (the source file's name without extension, e.g. <c>"LiberationSans-Regular"</c>). No reflection — a plain switch over the generated set.</summary>
    public static bool TryGetBlob(string faceKey, out ReadOnlySpan<byte> data)
    {
        switch (faceKey)
        {
            case "LiberationMono-Bold": data = LiberationMonoBoldBlob.Data; return true;
            case "LiberationMono-BoldItalic": data = LiberationMonoBoldItalicBlob.Data; return true;
            case "LiberationMono-Italic": data = LiberationMonoItalicBlob.Data; return true;
            case "LiberationMono-Regular": data = LiberationMonoRegularBlob.Data; return true;
            case "LiberationSans-Bold": data = LiberationSansBoldBlob.Data; return true;
            case "LiberationSans-BoldItalic": data = LiberationSansBoldItalicBlob.Data; return true;
            case "LiberationSans-Italic": data = LiberationSansItalicBlob.Data; return true;
            case "LiberationSans-Regular": data = LiberationSansRegularBlob.Data; return true;
            case "LiberationSerif-Bold": data = LiberationSerifBoldBlob.Data; return true;
            case "LiberationSerif-BoldItalic": data = LiberationSerifBoldItalicBlob.Data; return true;
            case "LiberationSerif-Italic": data = LiberationSerifItalicBlob.Data; return true;
            case "LiberationSerif-Regular": data = LiberationSerifRegularBlob.Data; return true;
            default: data = default; return false;
        }
    }
}
