// <auto-generated>
// Generated by tools/FontAssetGen — do not edit by hand.
// Source: PDFium core/fxge/fontdata/chromefontdata at commit 272ef3633b0f05896edfdc702d0328ed924e984e, extracted by scripts/fetch-foxit-fonts.sh (SHA-256 pinned there); license and copyright notices in NOTICE.
// Indexes every compiled-in substitute-font blob by face key by name (a plain switch, not
// reflection/Assembly.GetTypes — SubstituteFontStore's lookup stays AOT/trim-safe and clear
// of ReflectionBanTests without any gate change.
// </auto-generated>

namespace PlumePdf.Fonts.Substitute;

/// <summary>Name-keyed lookup over every compiled-in substitute-font blob this build generated.</summary>
internal static class SubstituteCffBlobs
{
    /// <summary>Every bundled face key this build compiled in, e.g. for AOT-smoke enumeration.</summary>
    public static readonly string[] FaceKeys = ["FoxitDingbats", "FoxitSymbol"];

    /// <summary>Looks up a compiled-in face's raw font bytes by key (the source file's name without extension, e.g. <c>"LiberationSans-Regular"</c>). No reflection — a plain switch over the generated set.</summary>
    public static bool TryGetBlob(string faceKey, out ReadOnlySpan<byte> data)
    {
        switch (faceKey)
        {
            case "FoxitDingbats": data = FoxitDingbatsBlob.Data; return true;
            case "FoxitSymbol": data = FoxitSymbolBlob.Data; return true;
            default: data = default; return false;
        }
    }
}
